import { ECommerceStore } from '@/models'

let e_commerce: ECommerceStore = {
  items: [
    {
      id: 'hJkLmNpQ',
      name: 'Camiseta blanca',
      description: 'Camiseta de algodón en color blanco con corte clásico.',
      price: 15.99,
      stock: 50,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Ropa/camiseta_blanca.jpeg',
    },
    {
      id: 'rStUvWxY',
      name: 'Zapatillas deportivas',
      description: 'Zapatillas deportivas con suela antideslizante en color gris.',
      price: 49.99,
      stock: 25,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Ropa/zapatillas_deportivas.jpg',
    },
    {
      id: 'zAbCdEfG',
      name: 'Reloj de pulsera',
      description: 'Reloj de pulsera con correa de cuero en color rose gold.',
      price: 79.99,
      stock: 10,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/reloj_pulsera.jpg',
    },
    {
      id: 'pQrStUvW',
      name: 'Bolso de mano',
      description: 'Bolso de mano de piel sintética en color lila.',
      price: 29.99,
      stock: 30,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/bolso_mano.png',
    },
    {
      id: 'mNoPqRsT',
      name: 'Lámpara de mesa',
      description: 'Lámpara de mesa con base de madera y pantalla blanca.',
      price: 39.99,
      stock: 20,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/lampra_mesa.jpg',
    },
    {
      id: 'gHiJkLmN',
      name: 'Juego de sábanas',
      description: 'Juego de sábanas de algodón en color azul para cama doble.',
      price: 59.99,
      stock: 15,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/juego_sabanas.jpg',
    },
    {
      id: 'tUvWxYzA',
      name: 'Cortina de baño',
      description: 'Cortina de baño con estampado asimetrico en tonos fríos.',
      price: 19.99,
      stock: 40,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/cortina_banio.jpg',
    },
    {
      id: 'cDeFgHiJ',
      name: 'Planta artificial',
      description: 'Planta artificial de hojas verdes en maceta de cerámica.',
      price: 12.99,
      stock: 60,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/planta_artificial.jpg',
    },
    {
      id: 'kLmNoPqR',
      name: 'Taza de café',
      description: 'Taza de cerámica con diseño minimalístico en color blanco.',
      price: 3.99,
      stock: 50,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/taza_cafe.jpg',
    },
    {
      id: 'a8s7d6f5',
      name: 'Libro de cocina',
      description: 'Libro de cocina con recetas japonesas.',
      price: 24.99,
      stock: 5,
      url: 'https://imagenes-bucket.s3.amazonaws.com/libros/libro_cocina.jpg',
    },
    {
      id: 'a4d6g8j9',
      name: 'Botines de caballero',
      description: 'Botines para caballero color marrón',
      price: 50,
      stock: 4,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Ropa/botines_hombre.jpg',
    },
    {
      id: 'x0v9n8s7',
      name: 'Sudadera unisex',
      description: 'Sudadera con gorra',
      price: 19.99,
      stock: 2,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Ropa/sudadera_mujer.jpg',
    },
    {
      id: 'a8s7d6c8',
      name: 'Libro de costura',
      description: 'Libro de cocina con recetas japonesas.',
      price: 24.99,
      stock: 6,
      url: 'https://imagenes-bucket.s3.amazonaws.com/libros/libro_costura.jpg',
    },
    {
      id: 'l1oi3u4',
      name: 'Juego de cubiertos',
      description: 'Juego de cubiertos de acero inoxidable color dorado.',
      price: 40,
      stock: 10,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/juego_cubiertos.jpg',
    },
    {
      id: 'jap7q9w9',
      name: 'Juego de té japonés',
      description: 'Juego de té japónes de cerámica con charola.',
      price: 70.99,
      stock: 4,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/juego_te.jpg',
    },
    {
      id: 't2u4p6p8',
      name: 'Juego de envases',
      description: 'Juego envases transparentes tipo tupper.',
      price: 31.99,
      stock: 6,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/juego_tupper.jpg',
    },
    {
      id: 'r5t6y7u8',
      name: 'Set nutribullet',
      description: 'Set nutribullet con vasos intercambiables.',
      price: 100,
      stock: 10,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/licuadora_nutribullet.jpg',
    },{
      id: 'sart1234',
      name: 'Juego de sartenes',
      description: 'Juego de sartenes de teflon de diferentes tamaños.',
      price: 50,
      stock: 5,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/sartenes.jpg',
    },
    {
      id: 'f5g6h7j8',
      name: 'Set copas para vino',
      description: 'Set copas para vino de vidrio cortado.',
      price: 40,
      stock: 16,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/set_copas.jpg',
    },
    {
      id: '1y2u3i4',
      name: 'Termo de acero',
      description: 'Termo de acero inoxidable de 800ml.',
      price: 25,
      stock: 6,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Cocina/termo.jpg',
    },
    {
      id: 'xbody123',
      name: 'Bolso crossbody',
      description: 'Bolso crossbody de piel sintética de color negro.',
      price: 25,
      stock: 19,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/bolso_crossbody.jpg',
    },
    {
      id: 's1m2m3w9',
      name: 'Lentes para natación',
      description: 'Lentes para natación antifugas transparentes.',
      price: 10,
      stock: 10,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/lentes_natacion.jpg',
    },
    {
      id: '2s3u4ng8',
      name: 'Lentes para sol',
      description: 'Lentes para sol de color gris.',
      price: 12,
      stock: 7,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/lentes_sol.jpg',
    },
    {
      id: 'g7y8m910',
      name: 'Mochila de gym',
      description: 'Mochila de gimnasio color rosa.',
      price: 50,
      stock: 12,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/mochila_gym.jpg',
    },
    {
      id: 'L4pt0p12',
      name: 'Mochila para laptop',
      description: 'Mochila para laptop color negra y rosa.',
      price: 40,
      stock: 14,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Accesorios/mochila_laptop.jpg',
    },
    {
      id: 'f6u7n8d4',
      name: 'Fundas para almohadas',
      description: 'Set de fundas de algodón para almohadas color azul marino.',
      price: 20,
      stock: 12,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/funda_almohada.jpg',
    },
    {
      id: 'b4s5u7r4',
      name: 'Bote de basura',
      description: 'Bote de basura de acero inoxidables color plateado.',
      price: 40,
      stock: 13,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/bote_basura.jpg',
    },
    {
      id: 'f5l6or7e',
      name: 'Florero de acrílico',
      description: 'Florero de acrílico transparente con forma de libro.',
      price: 15,
      stock: 12,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/florero_acrilico.jpg',
    },
    {
      id: 'j4b0n3r4',
      name: 'Jabonera para jabón líquido',
      description: 'Jabonera para jabón líquido color blanco y plateado.',
      price: 12,
      stock: 1,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/jabonera_liquido.jpg',
    },
    {
      id: 'p3r4c5h3',
      name: 'Perchero de pared',
      description: 'Perchero de pared de madera con cuatro ganchos.',
      price: 20,
      stock: 23,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/perchero.jpg',
    },
    {
      id: 't4p3t312',
      name: 'Tapete de entrada',
      description: 'Tapete de entrada con frase.',
      price: 12,
      stock: 2,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/tapete_entrada.jpg',
    },
    {
      id: 't04ll4as',
      name: 'Set de toallas',
      description: 'Set de toallas de algodón de color gris.',
      price: 40,
      stock: 20,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Hogar/toallas_banio.jpg',
    },
    {
      id: 'r3l0jd1g',
      name: 'Reloj despertador',
      description: 'Reloj despertador minimalista color negro.',
      price: 20,
      stock: 2,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Electronicos/reloj_despertador.jpg',
    },
    {
      id: 'aud1f0n0',
      name: 'Audifonos diadema',
      description: 'Audifonos de diadema con orejas de gato color morado.',
      price: 30,
      stock: 27,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Electronicos/audifonos_diadema.jpg',
    },
    {
      id: 'c4m4r4s3',
      name: 'Camara WiFi de seguridad',
      description: 'Camara WiFi de seguridad para interiores',
      price: 27,
      stock: 2,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Electronicos/camara_seguridad.jpg',
    },
    {
      id: 'pl4nch4v',
      name: 'Plancha de vapor',
      description: 'Plancha de vapor para ropa vertical.',
      price: 30,
      stock: 29,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Electronicos/plancha_vapor.jpg',
    },
    {
      id: 'r3l0jp4r',
      name: 'Reloj de pared',
      description: 'Reloj de pared moderno color rose gold.',
      price: 30,
      stock: 15,
      url: 'https://imagenes-bucket.s3.amazonaws.com/Electronicos/reloj_pared.jpg',
    },
  ],
}

export { e_commerce }
